[awesome]
src.git = "https://github.com/awesomeWM/awesome"
fetch.github = "awesomeWM/awesome"

[picom]
src.git = "https://github.com/ibhagwan/picom"
src.branch = "next-rebase"
fetch.github = "ibhagwan/picom"
