[awesome]
src.git = "https://github.com/awesomeWM/awesome"
fetch.github = "awesomeWM/awesome"

[picom]
src.git = "https://github.com/ibhagwan/picom"
src.branch = "next-rebase"
fetch.github = "ibhagwan/picom"

[spicetify-cli]
src.github = "khanhas/spicetify-cli"
fetch.github = "khanhas/spicetify-cli"

[spicetify-themes]
src.git = "https://github.com/morpheusthewhite/spicetify-themes"
fetch.github = "morpheusthewhite/spicetify-themes"

[catppuccin-spicetify]
src.git = "https://github.com/catppuccin/spicetify"
fetch.github = "catppuccin/spicetify"

[aerial-sddm-theme]
src.git = "https://github.com/3ximus/aerial-sddm-theme"
fetch.github = "3ximus/aerial-sddm-theme"
